added PageFactory task solution
tatsianabeliai/Task60 pull request #1
Opened 2017-07-06 18:49 UTC by tatsianabeliai

2017-08-01 12:39 UTC, EugenBorisik requested changes

2017-08-01 12:39 UTC, WGLife commented on src/main/java/TestBase.java
> +    public WebDriver driver;
Why these fields are public?

2017-08-01 12:39 UTC, WGLife commented on src/main/java/TestBase.java
> +    public TestBase(String baseUrl) {
Why is public?

2017-08-01 12:39 UTC, WGLife commented on src/main/java/TestBase.java
> +    public void waitForAllElements() {
Do not understand, why do you need such waiter?
You set up page load time and implicit waiter for your WebDriver instance, so remove this waiter.

2017-08-01 12:39 UTC, WGLife commented on src/main/java/pages/EmailsFactoryPage.java
> +public class EmailsFactoryPage {
Do not use plurals in names

2017-08-01 12:39 UTC, WGLife commented on src/main/java/pages/LoginFactoryPage.java
> +        Select loginDomainDrop = new Select(loginDomainDropDown);
Create private method (selectDomain(String domain) f.e.) for lines 32-33

2017-08-01 12:39 UTC, WGLife commented on src/test/java/PageFactoryTest.java
> +    public String domain = "mail.ru";
Make private. Make as constants (8-11)

2017-08-01 12:39 UTC, WGLife commented on src/main/java/pages/LoginFactoryPage.java
> +    public WebElement loginLink;
All WebElements should be private

2017-08-01 12:39 UTC, WGLife commented on src/test/java/PageFactoryTest.java
> +        Assert.assertTrue(emailsFactoryPage.loginedUserNameAtTop.isDisplayed(), "Logout link is displayed so user is not logged in");
All actions with WebElements should be encapsulated.

2017-08-01 12:39 UTC, WGLife commented on src/test/java/PageFactoryTest.java
> +        waitForAllElements();
Remove this method, if you need explicit waiter, it should be placed in the end of login(...) method

2017-08-01 12:39 UTC, WGLife commented on src/test/java/PageFactoryTest.java
> +        Assert.assertTrue(loginFactoryPage.loginLink.isDisplayed(), "No Login link so the user is logined");
Should be encapsulated

2017-08-01 12:56 UTC, tatsianabeliai commented on src/main/java/TestBase.java
> +    public WebDriver driver;
Made then private

2017-08-01 12:58 UTC, tatsianabeliai commented on src/main/java/TestBase.java
> +    public void waitForAllElements() {
done

2017-08-01 12:59 UTC, tatsianabeliai commented on src/main/java/TestBase.java
> +    public TestBase(String baseUrl) {
made protected

2017-08-01 13:00 UTC, tatsianabeliai commented on src/main/java/pages/EmailsFactoryPage.java
> +public class EmailsFactoryPage {
fixed

2017-08-01 13:31 UTC, tatsianabeliai commented on src/test/java/PageFactoryTest.java
> +        Assert.assertTrue(emailsFactoryPage.loginedUserNameAtTop.isDisplayed(), "Logout link is displayed so user is not logged in");
done

2017-08-01 13:31 UTC, tatsianabeliai commented on src/test/java/PageFactoryTest.java
> +        Assert.assertTrue(loginFactoryPage.loginLink.isDisplayed(), "No Login link so the user is logined");
done

2017-08-01 14:01 UTC, tatsianabeliai commented on src/main/java/pages/LoginFactoryPage.java
> +    public WebElement loginLink;
done

2017-08-01 14:02 UTC, tatsianabeliai commented on src/main/java/pages/LoginFactoryPage.java
> +        Select loginDomainDrop = new Select(loginDomainDropDown);
done

2017-08-01 14:03 UTC, tatsianabeliai commented on src/test/java/PageFactoryTest.java
> +    public String domain = "mail.ru";
done

2017-08-01 14:03 UTC, tatsianabeliai commented on src/test/java/PageFactoryTest.java
> +        waitForAllElements();
fixed

2017-08-07 07:16 UTC, EugenBorisik approved these changes

2017-08-07 07:17 UTC, merged